### ISSUE TITLE
Move Repository to cloudfoundry organization 

### ISSUE THREAD

**Issue by christopherclark** [cloudfoundry/bosh-alicloud-cpi-release#168]
Hello @xiaozhu36, 

The cloudfoundry-incubator GH organization only has a few active repositories left at this point, and will soon be archived. We'd like to discuss migrating this over to the cloudfoundry GH organization, presumably under the Foundational Infrastructure Working Group. Are you the sole maintainer of this repository at this point? 

Adding @rkoster for visibility here.

**Comment by xiaozhu36** [comment]
HI @christopherclark I am sorry for late reply. Yes, I am the maintainer and I think that is ok. I tried to transfer it, but I found I am not in cloudfoundry GH organization, does I need to apply joining it at first?

**Comment by beyhan** [comment]
Hi @xiaozhu36,

It makes sense to add the Ali Cloud CPI to the [Foundational Infrastructure Working Group](https://github.com/cloudfoundry/community/blob/main/toc/working-groups/foundational-infrastructure.md) because all other CPI are there. Each working group has its yaml section, which defines sub-areas for the working group, which repositories belong to a corresponding sub-area and who are the approvers and reviewers of that sub-area. For the Foundational Infrastructure WG you can find in the  [Roles & Technical Assets](https://github.com/cloudfoundry/community/blob/main/toc/working-groups/foundational-infrastructure.md#roles--technical-assets) section that information. Currently, all CPIs are located in the `VM deployment lifecycle (BOSH)` sub-area of the FI WG because they have the same set of approvers. For the Ali Cloud CPI we will have different set of approvers that is why I will suggest you to create a new sub-area for it, which you could manage. If you think this makes sense you could open a pr following [this](https://github.com/cloudfoundry/community/pull/784) one but for the FI WG. When you are added as approver for a sub-area you will get automatically member of the `cloudfoundry` GH organization.

**Comment by beyhan** [comment]
the new repository has been create https://github.com/cloudfoundry/bosh-alicloud-cpi-release and the move can be executed now.

**Comment by christopherclark** [comment]
@xiaozhu36 @beyhan The repository has now been transferred. I believe it may take a few hours for the automation to sync and add the correct permissions.

**Comment by xiaozhu36** [comment]
@christopherclark @beyhan Thanks a lot. In addition, I also need push permissions of other repos: [stemcells-alicloud-index](https://github.com/cloudfoundry/stemcells-alicloud-index) and [bosh-alicloud-light-stemcell-builder](https://github.com/cloudfoundry/bosh-alicloud-light-stemcell-builder) and can you help me to add?

**Comment by beyhan** [comment]
@xiaozhu36 could you please comment on https://github.com/cloudfoundry/community/pull/800 that you are OK with this. Merging that pr will give you [approver rights](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#approver) for the repositories.

**Comment by xiaozhu36** [comment]
@beyhan I noticed cloudfoundry/community#800 has been merged, but I still have not rights to merge the repo PR, like #169 . Do I need more works?

**Comment by beyhan** [comment]
I'm on it with https://github.com/cloudfoundry/community/pull/806. The wrong default branch in https://github.com/cloudfoundry/community/pull/798 broke our automation.

**Comment by beyhan** [comment]
@xiaozhu36 the change is merged now but if everything is fine it will take ~3 to 4 hour to apply the changes because we have many repos in our org.

**Comment by beyhan** [comment]
@xiaozhu36 you should have the approver rights now.

**Comment by bgandon** [comment]
Hi there, it seems the repo has been moved appropriately.
Can we close this issue?

**Comment by beyhan** [comment]
Closing as the move is done.
